// Package adapters provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package adapters

const (
	TokenScopes = "token.Scopes"
)

// Movie defines model for Movie.
type Movie struct {
	Director string `json:"director"`
	Id       string `json:"id"`
	Title    string `json:"title"`
}

// GetV1MoviesParams defines parameters for GetV1Movies.
type GetV1MoviesParams struct {
	// Title タイトル部分一致
	Title *string `form:"title,omitempty" json:"title,omitempty"`

	// Director 監督部分一致
	Director *string `form:"director,omitempty" json:"director,omitempty"`
	XUserID  string  `json:"X-User-ID"`
}
