version: "3"
services:
  movie-api:
    image: golang:1.20-alpine
    volumes:
      - ..:/go/src/github.com/monta-k/go-openapi-gen-example
    working_dir: /go/src/github.com/monta-k/go-openapi-gen-example/cmd/movie
    command:
      - go
      - run
      - main.go
    ports:
      - "8080:8080"
    environment:
      - PORT=8080